from .alltalk import NODE_CLASS_MAPPINGS as ALLTALK_NODE_CLASS_MAPPINGS
from .alltalk import NODE_DISPLAY_NAMES as ALLTALK_NODE_DISPLAY_NAMES
from .first_last_frame_selector import NODE_CLASS_MAPPINGS as FRAME_SELECTOR_NODE_CLASS_MAPPINGS
from .first_last_frame_selector import NODE_DISPLAY_NAME_MAPPINGS as FRAME_SELECTOR_NODE_DISPLAY_NAME_MAPPINGS
from .text_multiline import NODE_CLASS_MAPPINGS as TEXT_MULTILINE_NODE_CLASS_MAPPINGS
from .text_multiline import NODE_DISPLAY_NAME_MAPPINGS as TEXT_MULTILINE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {**ALLTALK_NODE_CLASS_MAPPINGS, **FRAME_SELECTOR_NODE_CLASS_MAPPINGS, **TEXT_MULTILINE_NODE_CLASS_MAPPINGS}
NODE_DISPLAY_NAMES = {**ALLTALK_NODE_DISPLAY_NAMES, **FRAME_SELECTOR_NODE_DISPLAY_NAME_MAPPINGS, **TEXT_MULTILINE_NODE_DISPLAY_NAME_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAMES"]
