from .alltalk import NODE_CLASS_MAPPINGS as ALLTALK_V1_MAPPINGS, NODE_DISPLAY_NAMES as ALLTALK_V1_NAMES
from .alltalk_v2 import NODE_CLASS_MAPPINGS as ALLTALK_V2_MAPPINGS, NODE_DISPLAY_NAMES as ALLTALK_V2_NAMES

NODE_CLASS_MAPPINGS = {**ALLTALK_V1_MAPPINGS, **ALLTALK_V2_MAPPINGS}
NODE_DISPLAY_NAMES = {**ALLTALK_V1_NAMES, **ALLTALK_V2_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAMES"]
